# Generated by Django 4.2.2 on 2023-06-22 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Hotel', 'هتل'), ('Apartment', 'آپارتمان'), ('Suite ', 'سوییت')], default='Hotel', max_length=12, verbose_name='نوع محل اقامت')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام اقامتگاه')),
                ('address', models.CharField(max_length=200)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True, verbose_name='تعداد اتاق')),
                ('hotel_stars', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'اقامتگاه',
                'verbose_name_plural': 'اقامتگاه ها',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(choices=[('one_way', 'رفت'), ('round_trip', 'برگشت')], max_length=20, verbose_name='نوع پرواز')),
                ('flight_number', models.CharField(max_length=50, verbose_name='شماره پرواز')),
                ('airport_of_origin', models.CharField(max_length=100, verbose_name='فرودگاه مبدا')),
                ('destination_airport', models.CharField(max_length=100, verbose_name='فرودگاه مقصد')),
                ('luggage_count', models.PositiveIntegerField(verbose_name='تعداد چمدان')),
                ('luggage_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='بار چمدان')),
                ('departure_date', models.DateField(verbose_name='تاریخ حرکت')),
                ('arrival_date', models.DateField(verbose_name='تاریخ رسیدن')),
                ('departure_time', models.TimeField(verbose_name='ساعت حرکت')),
                ('arrival_time', models.TimeField(verbose_name='ساعت رسیدن')),
                ('airline', models.CharField(max_length=100, verbose_name='شرکت هواپیمایی')),
                ('cabin_type', models.CharField(max_length=50, verbose_name='نوع کابین')),
                ('fare_class', models.CharField(max_length=50, verbose_name='کلاس نرخی')),
            ],
            options={
                'verbose_name': 'پرواز',
                'verbose_name_plural': 'پرواز ها',
            },
        ),
        migrations.CreateModel(
            name='RefundPolicyForFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancellation_notice_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicyForHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancellation_notice_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=100, verbose_name='مقصد')),
                ('departure_date', models.DateField(verbose_name='تاریخ رفت')),
                ('return_date', models.DateField(verbose_name='تاریخ برگشت')),
                ('rating', models.IntegerField(verbose_name='امتیاز')),
                ('seller', models.CharField(max_length=100, verbose_name='فروشنده تور')),
                ('services', models.TextField(verbose_name='خدمات تور')),
                ('price', models.IntegerField(verbose_name='قیمت تور')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_tours.accommodation', verbose_name='اطلاعات اقامتگاه')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_tours.flight', verbose_name='اطلاعات پرواز')),
            ],
            options={
                'verbose_name': 'تور',
                'verbose_name_plural': 'تور ها',
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='refund_policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_tours.refundpolicyforflight', verbose_name='قوانین استرداد پرواز'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='manage_tours.feature'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='refund_policy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_tours.refundpolicyforhotel'),
        ),
    ]
