# Generated by Django 4.2.2 on 2023-06-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'امکانات اقامتگاه', 'verbose_name_plural': 'امکانات اقامتگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='refundpolicyforflight',
            options={'verbose_name': 'قوانین استرداد پرواز', 'verbose_name_plural': 'قوانین استرداد پرواز'},
        ),
        migrations.AlterModelOptions(
            name='refundpolicyforhotel',
            options={'verbose_name': 'قوانین استرداد هتل', 'verbose_name_plural': 'قوانین استرداد هتل ها'},
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='polymorphic_ctype',
        ),
    ]
