# Generated by Django 4.2.2 on 2023-06-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0002_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='نام مکان')),
                ('day', models.IntegerField(verbose_name='روز چندم')),
                ('short_description', models.TextField(max_length=450, verbose_name='توضیحات کوتاه')),
            ],
            options={
                'verbose_name': 'برنامه سفر',
                'verbose_name_plural': 'برنامه های سفر',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='tour',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر اصلی'),
        ),
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.BooleanField(default=False, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='features',
            field=models.ManyToManyField(blank=True, to='manage_tours.feature'),
        ),
        migrations.CreateModel(
            name='TourImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_tours.tour', verbose_name='تور')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_tours.itinerary', verbose_name='برنامه سفر'),
        ),
    ]
