# Generated by Django 4.2.2 on 2023-06-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0003_itinerary_tour_description_tour_main_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='سوال')),
                ('answer', models.TextField(max_length=450, verbose_name='جواب')),
            ],
            options={
                'verbose_name': 'سوالات متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='faq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_tours.faq', verbose_name='سوالات متداول'),
        ),
    ]
