# Generated by Django 4.2.2 on 2023-06-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0004_faq_tour_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='مکان تور در نقشه'),
        ),
    ]
