# Generated by Django 4.2.2 on 2023-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0009_alter_tour_faq_alter_tour_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدت زمان'),
        ),
    ]
