# Generated by Django 4.2.2 on 2023-07-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0010_tour_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/tour', verbose_name='ویدیو تور'),
        ),
    ]
