# Generated by Django 4.2.2 on 2023-07-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0012_remove_tour_itinerary_itinerary_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='faq',
        ),
        migrations.AddField(
            model_name='faq',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_tours.tour', verbose_name='تور'),
        ),
    ]
