# Generated by Django 4.2.2 on 2023-07-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0013_remove_tour_faq_faq_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimagegallery',
            name='image',
            field=models.ImageField(upload_to='images/tour-image', verbose_name='تصویر'),
        ),
    ]
