# Generated by Django 4.2.2 on 2023-07-13 22:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0015_alter_tour_departure_date_alter_tour_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='short_description',
            field=tinymce.models.HTMLField(max_length=450, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
