# Generated by Django 4.2.2 on 2023-07-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0016_alter_itinerary_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='short_description',
            field=models.TextField(max_length=450, verbose_name='توضیحات کوتاه'),
        ),
    ]
