# Generated by Django 4.2.2 on 2023-07-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0017_alter_itinerary_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_tours.tour', verbose_name='تور'),
        ),
    ]
