# Generated by Django 4.2.2 on 2023-07-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0018_remove_tour_flight_flight_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_tours.itinerary', verbose_name='برنامه سفر'),
        ),
    ]
