# Generated by Django 4.2.2 on 2023-07-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0020_remove_faq_tour_tour_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='day',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='place',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='short_description',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='ItineraryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='نام مکان')),
                ('day', models.IntegerField(verbose_name='روز چندم')),
                ('short_description', models.TextField(max_length=450, verbose_name='توضیحات کوتاه')),
                ('Itinerar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_tours.itinerary', verbose_name='برنامه سفر')),
            ],
            options={
                'verbose_name': 'جزییات برنامه سفر',
                'verbose_name_plural': 'جزییات برنامه های سفر',
            },
        ),
    ]
