# Generated by Django 4.2.2 on 2023-07-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0021_remove_itinerary_day_remove_itinerary_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarydetail',
            name='Itinerar',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='detail',
            field=models.ManyToManyField(to='manage_tours.itinerarydetail', verbose_name='جزییات'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.ManyToManyField(blank=True, null=True, to='manage_tours.itinerary', verbose_name='برنامه سفر'),
        ),
    ]
