# Generated by Django 4.2.2 on 2023-07-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0022_remove_itinerarydetail_itinerar_itinerary_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourimagegallery',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='image_gallery',
            field=models.ManyToManyField(to='manage_tours.tourimagegallery', verbose_name='گالری تصویر'),
        ),
    ]
