# Generated by Django 4.2.2 on 2023-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0023_remove_tourimagegallery_tour_tour_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='accommodation',
        ),
        migrations.AddField(
            model_name='tour',
            name='accommodation',
            field=models.ManyToManyField(to='manage_tours.accommodation', verbose_name='اطلاعات اقامتگاه'),
        ),
    ]
