# Generated by Django 4.2.2 on 2023-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0024_remove_tour_accommodation_tour_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='faq',
        ),
        migrations.AddField(
            model_name='tour',
            name='faq',
            field=models.ManyToManyField(blank=True, null=True, to='manage_tours.faq', verbose_name='سوالات متداول'),
        ),
    ]
