# Generated by Django 4.2.2 on 2023-07-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0025_remove_tour_faq_tour_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='address',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
    ]
