# Generated by Django 4.2.2 on 2023-07-14 15:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0026_accommodation_city_alter_accommodation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarydetail',
            name='short_description',
            field=tinymce.models.HTMLField(max_length=450, verbose_name='توضیحات کوتاه'),
        ),
    ]
