# Generated by Django 4.2.2 on 2023-07-14 15:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0027_alter_itinerarydetail_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarydetail',
            name='short_description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات کوتاه'),
        ),
    ]
