# Generated by Django 4.2.2 on 2023-07-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tours', '0028_alter_itinerarydetail_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cabin_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع کابین'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='fare_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کلاس نرخی'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='luggage_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد چمدان'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='refund_policy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_tours.refundpolicyforflight', verbose_name='قوانین استرداد پرواز'),
        ),
    ]
