# Generated by Django 4.2.2 on 2023-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='logo_blog',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='logo_main_page',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(upload_to='site-setting', verbose_name='لوگو'),
        ),
    ]
