# Generated by Django 4.2.2 on 2023-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_remove_sitesetting_logo_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='positions',
            field=models.CharField(choices=[('blog', 'بلاگ'), ('article_detail', 'صفحه جزییات مقاله'), ('blog_category', 'صفحه دسته بندی بلاگ'), ('blog_tag', 'صفحه برچسب های بلاگ'), ('main_page', 'صفحه اصلی')], max_length=200, verbose_name='جایگاه قرار گیری'),
        ),
    ]
