# Generated by Django 4.2.2 on 2023-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_active_code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='کد فعال سازی ایمیل'),
        ),
    ]
