# Generated by Django 4.2.2 on 2023-07-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام و نام و خانوادگی')),
                ('Email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=300, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'لیست ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
            ],
        ),
    ]
