# Generated by Django 4.2.2 on 2023-07-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_rename_email_contactus_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
    ]
